### ISSUE TITLE
Backreferences in rewrites?

### ISSUE THREAD

**Issue by bard** [zeit/serve-handler#27]
I'm trying to rewrite everything under `/admin`, e.g.

- /admin => /
- /admin/index.html => /index.html
- /admin/static/style.css => /static/style.css
- /admin/static/main.js => /static/main.js

...and so on.

Can this be accomplished using `rewrites` in `serve.json` without specificying every possible path?

I tried the following but no luck:

```
{
  "rewrites": [{
    "source": "/admin/(.*)",
    "destination": "/$1"
  }]
}

**Comment by bard** [comment]
Thanks, I had seen that, but I assumed it would work as in Express routes in that it matches only one path component (i.e. would match `/foo/:bar` matches `/foo/index.js` but not `/foo/static/index.js`) and indeed it looks like that's the case:

```
arrow:/tmp/test$ ls -R public/
public/:
index.js  static

public/static:
style.css
arrow:/tmp/test$ cat serve.json
{
  "public": "public",
  "rewrites": [
    {
      "source": "/admin/:rest", "destination": "/:rest"
    }
  ]
}

arrow:/tmp/test$ serve &
[1] 17823
INFO: Discovered configuration in `serve.json`
INFO: Accepting connections at http://localhost:3000

arrow:/tmp/test$ curl http://localhost:3000/index.js
HTTP/1.1 200 OK
[...]
// this is /index.js

arrow:/tmp/test$ curl http://localhost:3000/admin/index.js
HTTP/1.1 200 OK
[...]
// this is /index.js
 
arrow:/tmp/test$ curl http://localhost:3000/static/style.css
HTTP/1.1 200 OK
[...]
/* this is /static/style.css */

arrow:/tmp/test$ curl http://localhost:3000/admin/static/style.css
HTTP/1.1 404 Not Found
[...]
<!DOCTYPE html><head> <meta name="viewport" content="width=device-width, [...]
```

**Comment by leo** [comment]
Yes, we implemented it a little differently because it was important for us to allow rewriting the entire ending of a path to a different one. If you want to restrict it, please create more rewrites afterwards that point the other paths to the right one. 

For every request, all rewrites that match the source are applied - so that should be easy. 👍

**Comment by erfangc** [comment]
this does not work if you are running `serve -s` as for some reason before the rewrites can happen `serve-handler` would actually end up serving index.html instead

```bash
user:~/environment/serve $ ls -lR
.:
total 8
drwxrwxr-x 3 ec2-user ec2-user 4096 Sep  6 15:52 public
-rw-rw-r-- 1 ec2-user ec2-user  114 Sep  6 18:23 serve.json

./public:
total 12
-rw-rw-r-- 1 ec2-user ec2-user  182 Sep  6 16:57 index.html
-rw-rw-r-- 1 ec2-user ec2-user   23 Sep  6 15:44 index.js
drwxrwxr-x 2 ec2-user ec2-user 4096 Sep  6 15:44 static

./public/static:
total 4
-rw-rw-r-- 1 ec2-user ec2-user 24 Sep  6 18:20 style.css
```

```bash
serve -s
curl localhost:8080/admin/index.js 
# Content of index.html instead
```

**Comment by AndyOGo** [comment]
[`path-to-regexp` supports **repeated segments**](https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp)

```js
const toPathRepeated = compile("/:segment+");

toPathRepeated({ segment: "foo" }); //=> "/foo"
toPathRepeated({ segment: ["a", "b", "c"] }); //=> "/a/b/c"
```

I think that should be the solution 🤔

**Comment by AaronBeaudoin** [comment]
@AndyOGo's solution looks like it wasn't tested, because with it I still get the same issue.

Here is my abridged `serve.json`:
```
{
  ...
  "rewrites": [
    {
      "source": "/some/path/:path+",
      "destination": "/:path"
    }
  ]
}
```

And here is my abridged `curl` output after running `npx serve`:

```
user@Machine project-root % curl -I http://localhost:3000/favicon.png                           
HTTP/1.1 200 OK
...

user@Machine project-root % curl -I http://localhost:3000/some/path/favicon.png      
HTTP/1.1 200 OK
...

user@Machine project-root % curl -I http://localhost:3000/assets/vendor.822f96e6.js                           
HTTP/1.1 200 OK
...

user@Machine project-root % curl -I http://localhost:3000/some/path/assets/vendor.822f96e6.js
HTTP/1.1 404 Not Found
...
```

**Comment by whydna** [comment]
So is there no way to do this?
